"""empty message

Revision ID: 4365e24a1565
Revises: 43807551a2fb
Create Date: 2021-12-08 11:12:50.120592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4365e24a1565'
down_revision = '43807551a2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'user_id')
    # ### end Alembic commands ###
