"""empty message

Revision ID: 865c52478d8d
Revises: 4365e24a1565
Create Date: 2021-12-08 19:40:00.511358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865c52478d8d'
down_revision = '4365e24a1565'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('month', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'month')
    # ### end Alembic commands ###
