"""empty message

Revision ID: ec5dd4141d82
Revises: 865c52478d8d
Create Date: 2021-12-08 22:16:43.680724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5dd4141d82'
down_revision = '865c52478d8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('expense_income_id_fkey', 'expense', type_='foreignkey')
    op.drop_column('expense', 'income_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('income_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('expense_income_id_fkey', 'expense', 'income', ['income_id'], ['id'])
    # ### end Alembic commands ###
